/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

public class Q2 {
  public static void main(String[] args) {
    int sum = 2;
    int firstNum = 1;
    int secondNum = 2;

    for (int i = 3; i <= 4000000;) {
      // If the number is even, add it to the sum
      if ((i % 2) == 0) {
        sum += i;
      }

      // Replace numbers
      firstNum = secondNum;
      secondNum = i;
      i = firstNum + secondNum;
    }
    System.out.println(sum);
  }
}
